export const SESSIONS_REPORT_HEADERS = [
  {
    text: "Client Name",
    align: "start",
    sortable: false,
    value: "client_name",
  },
  {
    text: "Brand Name",
    align: "start",
    sortable: false,
    value: "brand",
  },
  {
    text: "Game Name",
    align: "start",
    sortable: false,
    value: "game_name",
  },
  {
    text: "Studio Session ID",
    align: "start",
    sortable: false,
    value: "session_id",
  },
  {
    text: "Player ID",
    align: "start",
    sortable: false,
    value: "player_id",
  },
  {
    text: "Player Country",
    align: "start",
    sortable: false,
    value: "player_country",
  },
  {
    text: "Bets",
    align: "start",
    sortable: false,
    value: "total_bets",
  },
  {
    text: "Wins",
    align: "start",
    sortable: false,
    value: "total_wins",
  },
  {
    text: "Refound (€)",
    align: "start",
    sortable: false,
    value: "total_refunds",
  },
  {
    text: "Refounds Count",
    align: "start",
    sortable: false,
    value: "total_refunds_count",
  },
  {
    text: "GGR",
    align: "start",
    sortable: false,
    value: "ggr",
  },
  {
    text: "Bonus Bets",
    align: "start",
    sortable: false,
    value: "bonus_bets",
  },
  {
    text: "Bonus Wins",
    align: "start",
    sortable: false,
    value: "bonus_wins",
  },
  {
    text: "Bonus GGR",
    align: "start",
    sortable: false,
    value: "bonus_ggr",
  },
  {
    text: "RTP",
    align: "start",
    sortable: false,
    value: "rtp",
  },
  {
    text: "Total Spins",
    align: "start",
    sortable: false,
    value: "total_spins",
  },
  {
    text: "Time open",
    align: "start",
    sortable: false,
    value: "time_open",
  },
  {
    text: "Time closed",
    align: "start",
    sortable: false,
    value: "time_closed",
  },
];
