export const SUMMARY_REPORT_HEADERS = [
  {
    text: "Client ID - ClientName ",
    align: "start",
    sortable: false,
    value: "site_id",
  },
  {
    text: "Brands",
    align: "start",
    sortable: false,
    value: "total_brands",
  },
  {
    text: "Total Bets",
    align: "start",
    sortable: false,
    value: "total_bets",
  },
  {
    text: "Total Wins",
    align: "start",
    sortable: false,
    value: "total_wins",
  },
  {
    text: "Total Refunds",
    align: "start",
    sortable: false,
    value: "total_refunds",
  },
  {
    text: "GGR",
    align: "start",
    sortable: false,
    value: "ggr",
  },
  {
    text: "Bonus bets ",
    align: "start",
    sortable: false,
    value: "bonus_bets",
  },
  {
    text: "Bonus wins",
    align: "start",
    sortable: false,
    value: "bonus_wins",
  },
  {
    text: "Bonus GGR",
    align: "start",
    sortable: false,
    value: "bonus_ggr",
  },
  {
    text: "RTP",
    align: "start",
    sortable: false,
    value: "rtp",
  },
  {
    text: "AVG Bets",
    align: "start",
    sortable: false,
    value: "avg_bets",
  },
  {
    text: "Players",
    align: "start",
    sortable: false,
    value: "total_players",
  },
  {
    text: "Games",
    align: "start",
    sortable: false,
    value: "total_games",
  },
  {
    text: "Sessions",
    align: "start",
    sortable: false,
    value: "total_sessions",
  },
  {
    text: "Total Spins",
    align: "start",
    sortable: false,
    value: "total_spins",
  },
];

export const BRANDS_REPORT_HEADERS = [
  {
    text: "Brand Name",
    align: "start",
    sortable: false,
    value: "brand_id",
  },
  {
    text: "Total Bets",
    align: "start",
    sortable: false,
    value: "total_bets",
  },
  {
    text: "Total Wins",
    align: "start",
    sortable: false,
    value: "total_wins",
  },
  {
    text: "Total Refunds (€)",
    align: "start",
    sortable: false,
    value: "total_refunds",
  },
  {
    text: "GGR",
    align: "start",
    sortable: false,
    value: "ggr",
  },
  {
    text: "Bonus bets ",
    align: "start",
    sortable: false,
    value: "bonus_bets",
  },
  {
    text: "Bonus wins",
    align: "start",
    sortable: false,
    value: "bonus_wins",
  },
  {
    text: "Bonus GGR",
    align: "start",
    sortable: false,
    value: "bonus_ggr",
  },
  {
    text: "RTP",
    align: "start",
    sortable: false,
    value: "rtp",
  },
  {
    text: "AVG Bets",
    align: "start",
    sortable: false,
    value: "avg_bets",
  },
  {
    text: "Players",
    align: "start",
    sortable: false,
    value: "total_players",
  },
  {
    text: "Games",
    align: "start",
    sortable: false,
    value: "total_games",
  },
  {
    text: "Sessions",
    align: "start",
    sortable: false,
    value: "total_sessions",
  },
  {
    text: "Total Spins",
    align: "start",
    sortable: false,
    value: "total_spins",
  },
];

export const GAMES_REPORT_HEADERS = [
  {
    text: "Game ID",
    align: "start",
    sortable: false,
    value: "game_id",
  },
  {
    text: "Game Title",
    align: "start",
    sortable: false,
    value: "game_name",
  },
  {
    text: "Studio",
    align: "start",
    sortable: false,
    value: "studio",
  },
  {
    text: "Brands",
    align: "start",
    sortable: false,
    value: "total_brands",
  },
  {
    text: "Total Bets",
    align: "start",
    sortable: false,
    value: "total_bets",
  },
  {
    text: "Total Wins",
    align: "start",
    sortable: false,
    value: "total_wins",
  },
  {
    text: "Total Refunds (€)",
    align: "start",
    sortable: false,
    value: "total_refunds",
  },
  {
    text: "GGR",
    align: "start",
    sortable: false,
    value: "ggr",
  },
  {
    text: "Bonus bets ",
    align: "start",
    sortable: false,
    value: "bonus_bets",
  },
  {
    text: "Bonus wins",
    align: "start",
    sortable: false,
    value: "bonus_wins",
  },
  {
    text: "Bonus GGR",
    align: "start",
    sortable: false,
    value: "bonus_ggr",
  },
  {
    text: "RTP",
    align: "start",
    sortable: false,
    value: "rtp",
  },
  {
    text: "AVG Bets",
    align: "start",
    sortable: false,
    value: "avg_bets",
  },
  {
    text: "Players",
    align: "start",
    sortable: false,
    value: "total_players",
  },
  {
    text: "Sessions",
    align: "start",
    sortable: false,
    value: "total_sessions",
  },
  {
    text: "Total Spins",
    align: "start",
    sortable: false,
    value: "total_spins",
  },
];

export const PLAYERS_REPORT_HEADERS = [
  {
    text: "Player ID",
    align: "start",
    sortable: false,
    value: "player_id",
  },
  {
    text: "Client Name",
    align: "start",
    sortable: false,
    value: "client_name",
  },
  {
    text: "Brand",
    align: "start",
    sortable: false,
    value: "brand",
  },
  {
    text: "Total Bets",
    align: "start",
    sortable: false,
    value: "total_bets",
  },
  {
    text: "Total Wins",
    align: "start",
    sortable: false,
    value: "total_wins",
  },
  {
    text: "Total Refunds (€)",
    align: "start",
    sortable: false,
    value: "total_refunds",
  },
  {
    text: "GGR",
    align: "start",
    sortable: false,
    value: "ggr",
  },
  {
    text: "Bonus bets ",
    align: "start",
    sortable: false,
    value: "bonus_bets",
  },
  {
    text: "Bonus wins",
    align: "start",
    sortable: false,
    value: "bonus_wins",
  },
  {
    text: "Bonus GGR",
    align: "start",
    sortable: false,
    value: "bonus_ggr",
  },
  {
    text: "Games",
    align: "start",
    sortable: false,
    value: "total_games",
  },
  {
    text: "Studios",
    align: "start",
    sortable: false,
    value: "total_studios",
  },
  {
    text: "Sessions",
    align: "start",
    sortable: false,
    value: "total_sessions",
  },
  {
    text: "Spins",
    align: "start",
    sortable: false,
    value: "total_spins",
  },
  {
    text: "LTV",
    align: "start",
    sortable: false,
    value: "ltv",
  },
];
