export const GAMES_REPORT_HEADERS = [
  {
    text: "Game ID",
    align: "start",
    sortable: false,
    value: "game_id",
  },
  {
    text: "Game Title",
    align: "start",
    sortable: false,
    value: "game_name",
  },
  {
    text: "Studio",
    align: "start",
    sortable: false,
    value: "studio",
  },
  {
    text: "Brands",
    align: "start",
    sortable: false,
    value: "total_brands",
  },
  {
    text: "Total Bets",
    align: "start",
    sortable: false,
    value: "total_bets",
  },
  {
    text: "Total Wins",
    align: "start",
    sortable: false,
    value: "total_wins",
  },
  {
    text: "Total Refounds",
    align: "start",
    sortable: false,
    value: "total_refunds",
  },
  {
    text: "GGR",
    align: "start",
    sortable: false,
    value: "ggr",
  },
  {
    text: "Bonus bets",
    align: "start",
    sortable: false,
    value: "bonus_bets",
  },
  {
    text: "Bonus wins",
    align: "start",
    sortable: false,
    value: "bonus_wins",
  },
  {
    text: "Bonus GGR",
    align: "start",
    sortable: false,
    value: "bonus_ggr",
  },
  {
    text: "RTP%",
    align: "start",
    sortable: false,
    value: "rtp",
  },
  {
    text: "AVG Bets",
    align: "start",
    sortable: false,
    value: "avg_bets",
  },
  {
    text: "Players",
    align: "start",
    sortable: false,
    value: "total_players",
  },
  {
    text: "Sessions Number",
    align: "start",
    sortable: false,
    value: "total_sessions",
  },
  {
    text: "Total Spins",
    align: "start",
    sortable: false,
    value: "total_spins",
  },
];

export const PLAYERS_REPORT_HEADERS = [
  {
    text: "Player ID",
    align: "start",
    sortable: false,
    value: "player_id",
  },
  {
    text: "Brand Name",
    align: "start",
    sortable: false,
    value: "brand",
  },
  {
    text: "Total Bets",
    align: "start",
    sortable: false,
    value: "total_bets",
  },
  {
    text: "Total Wins",
    align: "start",
    sortable: false,
    value: "total_wins",
  },
  {
    text: "Total Refounds",
    align: "start",
    sortable: false,
    value: "total_refunds",
  },
  {
    text: "GGR",
    align: "start",
    sortable: false,
    value: "ggr",
  },
  {
    text: "Bonus bets",
    align: "start",
    sortable: false,
    value: "bonus_bets",
  },
  {
    text: "Bonus wins",
    align: "start",
    sortable: false,
    value: "bonus_wins",
  },
  {
    text: "Bonus GGR",
    align: "start",
    sortable: false,
    value: "bonus_ggr",
  },
  {
    text: "RTP%",
    align: "start",
    sortable: false,
    value: "rtp",
  },
  {
    text: "AVG Bets",
    align: "start",
    sortable: false,
    value: "avg_bets",
  },
  {
    text: "Games",
    align: "start",
    sortable: false,
    value: "games",
  },
  {
    text: "Studios",
    align: "start",
    sortable: false,
    value: "total_studios",
  },
  {
    text: "Sessions Number",
    align: "start",
    sortable: false,
    value: "total_sessions",
  },
  {
    text: "Total Spins",
    align: "start",
    sortable: false,
    value: "total_spins",
  },
];

export const SESSIONS_REPORT_HEADERS = [
  {
    text: "Session ID",
    align: "start",
    sortable: false,
    value: "session_id",
  },
  {
    text: "Player ID",
    align: "start",
    sortable: false,
    value: "player_id",
  },
  {
    text: "Brand Name",
    align: "start",
    sortable: false,
    value: "brand",
  },
  {
    text: "Player Country",
    align: "start",
    sortable: false,
    value: "player_country",
  },
  {
    text: "Bets",
    align: "start",
    sortable: false,
    value: "total_bets",
  },
  {
    text: "Wins",
    align: "start",
    sortable: false,
    value: "total_wins",
  },
  {
    text: "Refound (€)",
    align: "start",
    sortable: false,
    value: "total_refunds",
  },
  {
    text: "Refounds Count",
    align: "start",
    sortable: false,
    value: "total_refunds_count",
  },
  {
    text: "GGR",
    align: "start",
    sortable: false,
    value: "ggr",
  },
  {
    text: "Bonus Bets",
    align: "start",
    sortable: false,
    value: "bonus_bets",
  },
  {
    text: "Bonus Wins",
    align: "start",
    sortable: false,
    value: "bonus_wins",
  },
  {
    text: "Bonus GGR",
    align: "start",
    sortable: false,
    value: "bonus_ggr",
  },
  {
    text: "RTP",
    align: "start",
    sortable: false,
    value: "rtp",
  },
  {
    text: "Total Spins",
    align: "start",
    sortable: false,
    value: "total_spins",
  },
  {
    text: "Time open",
    align: "start",
    sortable: false,
    value: "time_open",
  },
  {
    text: "Time closed",
    align: "start",
    sortable: false,
    value: "time_closed",
  },
];
